# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-23 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190723_2140'),
        ('restaurants', '0002_linemember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linemember',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='line',
            field=models.ManyToManyField(related_name='restaurant', to='users.LineMember'),
        ),
        migrations.DeleteModel(
            name='LineMember',
        ),
    ]
