# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_seateduser'),
        ('restaurants', '0004_restaurant_seatuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='party',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table', to='users.SeatedUser'),
        ),
    ]
