# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_table_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='seatUser',
            field=models.ManyToManyField(related_name='restaurant', to='users.SeatedUser'),
        ),
    ]
