# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-20 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantQueueApp', '0002_auto_20190720_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurantQueueApp.Restaurant'),
            preserve_default=False,
        ),
    ]
