# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-23 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190723_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='restaurants.LineMember'),
        ),
    ]
