# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190723_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='line',
        ),
        migrations.AddField(
            model_name='linemember',
            name='member',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='line', to='users.User'),
            preserve_default=False,
        ),
    ]
