# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190724_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linemember',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line', to='users.User'),
        ),
    ]
