# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190724_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seatUser', to='users.User')),
            ],
        ),
    ]
