# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_seateduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seateduser',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seatUser', to='users.User'),
        ),
    ]
