# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190725_1820'),
        ('users', '0010_auto_20190725_2007'),
    ]

    operations = [
    ]
