# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-27 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20190727_2355'),
        ('users', '0010_auto_20190725_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linemember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='seateduser',
            name='member',
        ),
        migrations.AddField(
            model_name='user',
            name='partySize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='restaurants.Restaurant'),
        ),
        migrations.AddField(
            model_name='user',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='restaurants.Table'),
        ),
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='LineMember',
        ),
        migrations.DeleteModel(
            name='SeatedUser',
        ),
    ]
