# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-28 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190727_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='table',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='restaurants.Table'),
        ),
    ]
