# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-30 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190728_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isTemp',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
